---

title: Метамем
timezone: UTC
description: by Indexmod
url: https://metamem.cf

show_rss: true
show_sidebar: false
show_downloads: false
show_title: false
show_description: false
git_branch: master

theme: jekyll-theme-minimal

include: ['.htaccess']


use_github_wiki: false
custom_head: false
custom_sidebar: false
custom_footer: false


media: '/images'

# Podcast Feed Settings

email:          indexmod@ya.ru
description:    "Test podcast engine"
subtitle:       "Listen to me"
lang:           RU
author:         Andrei Dei
copyright:      "&#x2117; &amp; &#xA9; 2015"



feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
