---

title: Podcast
name: Имя
timezone: UTC
description: by Indexmod
url: https://indexmod.github.io/podcast/
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1

show_sidebar: false
show_downloads: false
show_title: false
show_description: false
git_branch: master

theme: jekyll-theme-minimal

include: ['.htaccess']

use_github_wiki: false
custom_head: false
custom_sidebar: false
custom_footer: false


media: '/images'
rss: '/_site'

  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
    - /assets
    - 404.md
    - README.md
    - sitemap.xml
    - robots.txt
    - redirects.json
