---

title: Pod
timezone: UTC
description: by Indexmod
url: https://indexmod.github.io

show_rss: true
show_sidebar: false
show_downloads: false
show_title: false
show_description: false
git_branch: master

theme: jekyll-theme-minimal

include: ['.htaccess']
exclude: ['/assets/css/style.scss']

use_github_wiki: false
custom_head: false
custom_sidebar: false
custom_footer: false


media: '/images'



feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
